/* Auto-generated by genmsg_cpp for file /home/mosaic/fuerte_workspace/koki/msg/KokiMsg.msg */
#ifndef KOKI_MESSAGE_KOKIMSG_H
#define KOKI_MESSAGE_KOKIMSG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace koki
{
template <class ContainerAllocator>
struct KokiMsg_ {
  typedef KokiMsg_<ContainerAllocator> Type;

  KokiMsg_()
  : header()
  , tags()
  {
  }

  KokiMsg_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , tags(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _tags_type;
  std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  tags;


  typedef boost::shared_ptr< ::koki::KokiMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::koki::KokiMsg_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct KokiMsg
typedef  ::koki::KokiMsg_<std::allocator<void> > KokiMsg;

typedef boost::shared_ptr< ::koki::KokiMsg> KokiMsgPtr;
typedef boost::shared_ptr< ::koki::KokiMsg const> KokiMsgConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::koki::KokiMsg_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::koki::KokiMsg_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace koki

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::koki::KokiMsg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::koki::KokiMsg_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::koki::KokiMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fe7110c393ddc1d808f67f0d26385fab";
  }

  static const char* value(const  ::koki::KokiMsg_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xfe7110c393ddc1d8ULL;
  static const uint64_t static_value2 = 0x08f67f0d26385fabULL;
};

template<class ContainerAllocator>
struct DataType< ::koki::KokiMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "koki/KokiMsg";
  }

  static const char* value(const  ::koki::KokiMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::koki::KokiMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
uint16[] tags\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::koki::KokiMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::koki::KokiMsg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::koki::KokiMsg_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::koki::KokiMsg_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.tags);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct KokiMsg_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::koki::KokiMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::koki::KokiMsg_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "tags[]" << std::endl;
    for (size_t i = 0; i < v.tags.size(); ++i)
    {
      s << indent << "  tags[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.tags[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // KOKI_MESSAGE_KOKIMSG_H

